/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeatherTextImport } from './routes/weather.$text'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeatherTextRoute = WeatherTextImport.update({
  id: '/weather/$text',
  path: '/weather/$text',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/weather/$text': {
      id: '/weather/$text'
      path: '/weather/$text'
      fullPath: '/weather/$text'
      preLoaderRoute: typeof WeatherTextImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/weather/$text': typeof WeatherTextRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/weather/$text': typeof WeatherTextRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/weather/$text': typeof WeatherTextRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/weather/$text'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/weather/$text'
  id: '__root__' | '/' | '/weather/$text'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeatherTextRoute: typeof WeatherTextRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeatherTextRoute: WeatherTextRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/weather/$text"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/weather/$text": {
      "filePath": "weather.$text.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
